server:
  port: 8763
spring:
  application:
    name: travel-management-config-server
  cloud:
    config:
      server:
        git:
          uri: file:///D:/141879/TravelManagementSystem/config-repo/
          clone-on-start: false
          force-pull: true
          search-paths: '{application}'
          default-label: master
  security:
    user:
      name: root
      password: root
      
