server:
  port: 8763
spring:
  application:
    name: travel-management-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/suresram/travel-management-config-repo.git
          clone-on-start: false
          force-pull: true
          search-paths: '{application}'
          default-label: master
  security:
    user:
      name: root
      password: root
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always        
eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://travel-management-eureka-server:8761/eureka      
